version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "notes"
    volumes:
      - ./notes.sql:/docker-entrypoint-initdb.d/init.sql
      # - db_data:/var/lib/mysql
    networks:
      - shared

  app:
    image: prova
    environment:
      DB_HOST: db
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - shared

networks:
  shared:
    driver: bridge